"""
配置模块包
包含：
- settings: 全局配置和常量
"""

from .settings import (
    OPENAI_API_KEY,
    OPENAI_BASE_URL,
    OPENAI_MODEL,
    AI_SYSTEM_PROMPT,
    WECHAT_WINDOW_NAME,
    WECHAT_SEARCH_NAME,
    WECHAT_MESSAGE_LIST_NAME,
    DEFAULT_AUTO_REPLY_START_TIME,
    DEFAULT_AUTO_REPLY_END_TIME,
    THREAD_CHECK_INTERVAL,
    MONITOR_CHECK_INTERVAL,
    UI_FILE_PATH
)

__all__ = [
    'OPENAI_API_KEY',
    'OPENAI_BASE_URL',
    'OPENAI_MODEL',
    'AI_SYSTEM_PROMPT',
    'WECHAT_WINDOW_NAME',
    'WECHAT_SEARCH_NAME',
    'WECHAT_MESSAGE_LIST_NAME',
    'DEFAULT_AUTO_REPLY_START_TIME',
    'DEFAULT_AUTO_REPLY_END_TIME',
    'THREAD_CHECK_INTERVAL',
    'MONITOR_CHECK_INTERVAL',
    'UI_FILE_PATH'
]